name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Create gh-pages branch if it doesn't exist
      run: |
        git fetch origin
        if git show-ref --verify --quiet refs/heads/gh-pages; then
          echo "Branch exists"
        else
          git checkout --orphan gh-pages
          git rm -rf .
          touch .nojekyll
          git add .nojekyll
          git commit -m "Initial commit on gh-pages branch"
          git push origin gh-pages
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /workspaces/SpaceInvaders
